In [24]:
import numpy as np
import pandas as pd
import matplotlib as plt
import plotly.graph_objects as pltgraph

In [25]:
datasets = pd.read_csv('main_dataset.csv')
datasets.head(10)


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            2      138             62             35        0  33.6   
1            0       84             82             31      125  38.2   
2            0      145              0              0        0  44.2   
3            0      135             68             42      250  42.3   
4            1      139             62             41      480  40.7   
5            0      173             78             32      265  46.5   
6            4       99             72             17        0  25.6   
7            8      194             80              0        0  26.1   
8            2       83             65             28       66  36.8   
9            2       89             90             30        0  33.5   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.127   47        1  
1                     0.233   23        0  
2                     0.630   31        1  
3                     0.365   24        1  
4                     0.536   21        0  
5                     1.159   58        0  
6                     0.294   28        0  
7                     0.551   67        0  
8                     0.629   24        0  
9                     0.292   42        0

In [26]:
datasets.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [11]:
datasets[datasets.duplicated()]

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
483             0       84             82             31      125  38.2   
484             0      145              0              0        0  44.2   
485             0      135             68             42      250  42.3   
486             1      139             62             41      480  40.7   
487             0      173             78             32      265  46.5   
...           ...      ...            ...            ...      ...   ...   
2763           10      101             76             48      180  32.9   
2764            2      122             70             27        0  36.8   
2765            5      121             72             23      112  26.2   
2766            1      126             60              0        0  30.1   
2767            1       93             70             31        0  30.4   

      DiabetesPedigreeFunction  Age  Outcome  
483                      0.233   23        0  
484                      0.630   31        1  
485                      0.365   24        1  
486                      0.536   21        0  
487                      1.159   58        0  
...                        ...  ...      ...  
2763                     0.171   63        0  
2764                     0.340   27        0  
2765                     0.245   30        0  
2766                     0.349   47        1  
2767                     0.315   23        0  

[1990 rows x 9 columns]

In [8]:
datasets.describe()

Pregnancies      Glucose  BloodPressure  SkinThickness      Insulin  \
count  2768.000000  2768.000000    2768.000000    2768.000000  2768.000000   
mean      3.742775   121.102601      69.134393      20.824422    80.127890   
std       3.323801    32.036508      19.231438      16.059596   112.301933   
min       0.000000     0.000000       0.000000       0.000000     0.000000   
25%       1.000000    99.000000      62.000000       0.000000     0.000000   
50%       3.000000   117.000000      72.000000      23.000000    37.000000   
75%       6.000000   141.000000      80.000000      32.000000   130.000000   
max      17.000000   199.000000     122.000000     110.000000   846.000000   

               BMI  DiabetesPedigreeFunction          Age      Outcome  
count  2768.000000               2768.000000  2768.000000  2768.000000  
mean     32.137392                  0.471193    33.132225     0.343931  
std       8.076127                  0.325669    11.777230     0.475104  
min       0.000000                  0.078000    21.000000     0.000000  
25%      27.300000                  0.244000    24.000000     0.000000  
50%      32.200000                  0.375000    29.000000     0.000000  
75%      36.625000                  0.624000    40.000000     1.000000  
max      80.600000                  2.420000    81.000000     1.000000

In [27]:
target = datasets['Outcome']
target

0       1
1       0
2       1
3       1
4       0
       ..
2763    0
2764    0
2765    0
2766    1
2767    0
Name: Outcome, Length: 2768, dtype: int64

In [28]:
inputs = datasets.drop("Outcome", axis = 'columns')
inputs.shape

(2768, 8)

In [29]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x_scaled = scaler.fit_transform(inputs)
x_scaled[:5]

array([[-0.52442655,  0.52753727, -0.37104257,  0.88284535, -0.71363302,
         0.18113541, -1.05706998,  1.17772008],
       [-1.12625601, -1.15834425,  0.66910917,  0.63372807,  0.39963887,
         0.75081826, -0.73152716, -0.86047875],
       [-1.12625601,  0.74607746, -3.59551293, -1.29693082, -0.71363302,
         1.49388285,  0.48772287, -0.18107914],
       [-1.12625601,  0.43387718, -0.05899705,  1.31880058,  1.51291076,
         1.25857906, -0.3261342 , -0.7755538 ],
       [-0.82534128,  0.55875729, -0.37104257,  1.25652126,  3.56133105,
         1.06042851,  0.19903394, -1.03032866]])

In [16]:
x_scaled.shape

(2768, 8)

In [30]:
from sklearn.model_selection import train_test_split
xtrain, xtest,ytrain, ytest = train_test_split(x_scaled, target, stratify=target, random_state=42)

In [18]:
xtrain.shape

(2076, 8)

In [19]:
xtest.shape


(692, 8)

In [20]:
ytrain.value_counts()

0    1362
1     714
Name: Outcome, dtype: int64

In [21]:
714/1362

0.5242290748898678

In [121]:
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.datasets import make_regression

# Define the base models
model1 = LinearRegression()
model2 = SVR()
model3 = DecisionTreeRegressor()

# x,y = make_regression(n_samples=100, n_features=4,
#                        n_informative=2, n_targets=1,
#                       random_state=0, shuffle=False)


In [31]:
from sklearn import svm
from sklearn.model_selection import cross_val_score
model = svm.SVC(kernel='linear',gamma='auto',C=2)
model.fit(xtrain, ytrain)
ypredict = model.predict(xtest)

In [32]:
scores =  cross_val_score(model, xtrain, ytrain,cv= 5)
scores

array([0.80048077, 0.7373494 , 0.77831325, 0.78795181, 0.78313253])

In [33]:
scores.mean()

0.7774455514365154

In [37]:
from sklearn.svm import SVC
from sklearn.ensemble import BaggingClassifier
#  from sklearn.datasets import make_classification
#  X, y = make_classification(n_samples=100, n_features=4,
#                             n_informative=2, n_redundant=0,
#                             random_state=0, shuffle=False)
clf = BaggingClassifier(base_estimator=SVC(),
                         n_estimators=10, random_state=5).fit(xtrain, ytrain)




In [40]:
Bscores =  cross_val_score(clf, xtrain, ytrain,cv= 5)
Bscores

array([0.83653846, 0.77831325, 0.82891566, 0.82650602, 0.84096386])

In [41]:
Bscores.mean()

0.8222474513438369

In [55]:
y = clf.predict(xtest)
y.sum()


190

In [49]:
from sklearn.metrics import classification_report
print(classification_report(ytest, ypredict))

              precision    recall  f1-score   support

           0       0.79      0.89      0.84       454
           1       0.72      0.56      0.63       238

    accuracy                           0.77       692
   macro avg       0.76      0.72      0.73       692
weighted avg       0.77      0.77      0.77       692



In [47]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier
bag_model = BaggingClassifier(
    base_estimator = DecisionTreeClassifier(),
   n_estimators = 100,
    max_samples = 0.8,
    oob_score = True,
    random_state = 0
)
bag_model.fit(xtrain, ytrain)
bag_model.oob_score_

0.7534722222222222

In [48]:
bag_model.score(xtest, ytest)

0.7760416666666666

In [54]:
from sklearn.model_selection import cross_val_score

bag_model = BaggingClassifier(
    base_estimator = DecisionTreeClassifier(),
   n_estimators = 100,
    max_samples = 0.8,
    oob_score = True,
    random_state = 0
)
scores =  cross_val_score(bag_model, inputs, target,cv= 5)
scores

array([0.75324675, 0.72727273, 0.74675325, 0.82352941, 0.73856209])

In [55]:
scores.mean()

0.7578728461081402

In [56]:
# from sklearn.linear_model import LinearRegression
# from sklearn.tree import DecisionTreeClassifier
# from sklearn.svm import SVC
# from sklearn.ensemble import BaggingRegressor


# # Define the base models
# model1 = LinearRegression()
# model2 = SVC()
# model3 = DecisionTreeClassifier()

# bag_model1 = BaggingClassifier(
#     base_estimator = DecisionTreeClassifier(),
#     n_estimators = 100,
#     max_samples = 0.8,
#     oob_score = True,
#     random_state = 0
# )
# bag_model1.fit(xtrain, ytrain)
# bag_model.oob_score_

In [ ]:
# draw confusion matrix
import seaborn as sns
sns.heatmap(pd.DataFrame(cm), annot=True, cmap="YlGnBu" ,fmt='g')
plt.tight_layout()
plt.title('Confusion matrix', y=1.1)
plt.ylabel('Actual label')
plt.xlabel('Predicted label')
plt.show()
